Update `model_generate` to fix error: `'tuple' object has no attribute 'logits'`
We need to force `moded_generate` to output logits so that `linux_train.py` can reference the `logits` attribute

Signed-off-by: Courtney Pacheco <6019922+courtneypacheco@users.noreply.github.com>